/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *backspace;
  GtkWidget *Clearentry;
  GtkWidget *clear;
  GtkWidget *sign;
  GtkWidget *division;
  GtkWidget *nine;
  GtkWidget *eight;
  GtkWidget *seven;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *mul;
  GtkWidget *subtrac;
  GtkWidget *three;
  GtkWidget *two;
  GtkWidget *one;
  GtkWidget *zero;
  GtkWidget *dot;
  GtkWidget *equal;
  GtkWidget *addition;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (window1), 200, 260);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 88, 32);
  gtk_widget_set_size_request (entry1, 192, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  backspace = gtk_button_new_with_mnemonic (_("BKSP"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 24, 112);
  gtk_widget_set_size_request (backspace, 64, 27);

  Clearentry = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (Clearentry);
  gtk_fixed_put (GTK_FIXED (fixed1), Clearentry, 112, 112);
  gtk_widget_set_size_request (Clearentry, 64, 27);

  clear = gtk_button_new_with_mnemonic (_("clr"));
  gtk_widget_show (clear);
  gtk_fixed_put (GTK_FIXED (fixed1), clear, 200, 112);
  gtk_widget_set_size_request (clear, 64, 27);

  sign = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (sign);
  gtk_fixed_put (GTK_FIXED (fixed1), sign, 296, 112);
  gtk_widget_set_size_request (sign, 64, 27);

  division = gtk_button_new_with_mnemonic (_("\303\267"));
  gtk_widget_show (division);
  gtk_fixed_put (GTK_FIXED (fixed1), division, 296, 160);
  gtk_widget_set_size_request (division, 64, 27);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 200, 160);
  gtk_widget_set_size_request (nine, 64, 27);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 112, 160);
  gtk_widget_set_size_request (eight, 64, 27);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 24, 160);
  gtk_widget_set_size_request (seven, 64, 27);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 24, 216);
  gtk_widget_set_size_request (four, 64, 27);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 112, 216);
  gtk_widget_set_size_request (five, 72, 27);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 200, 216);
  gtk_widget_set_size_request (six, 72, 27);

  mul = gtk_button_new_with_mnemonic (_("\303\227"));
  gtk_widget_show (mul);
  gtk_fixed_put (GTK_FIXED (fixed1), mul, 296, 216);
  gtk_widget_set_size_request (mul, 72, 27);

  subtrac = gtk_button_new_with_mnemonic (_("\342\210\222"));
  gtk_widget_show (subtrac);
  gtk_fixed_put (GTK_FIXED (fixed1), subtrac, 296, 264);
  gtk_widget_set_size_request (subtrac, 72, 27);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 200, 264);
  gtk_widget_set_size_request (three, 72, 27);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 112, 264);
  gtk_widget_set_size_request (two, 72, 27);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 24, 264);
  gtk_widget_set_size_request (one, 72, 27);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 24, 312);
  gtk_widget_set_size_request (zero, 72, 27);

  dot = gtk_button_new_with_mnemonic (_("\342\200\242"));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 112, 312);
  gtk_widget_set_size_request (dot, 72, 27);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 200, 312);
  gtk_widget_set_size_request (equal, 72, 27);

  addition = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (addition);
  gtk_fixed_put (GTK_FIXED (fixed1), addition, 296, 312);
  gtk_widget_set_size_request (addition, 72, 27);

  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) Clearentry, "clicked",
                    G_CALLBACK (on_Clearentry_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear, "clicked",
                    G_CALLBACK (on_clear_clicked),
                    NULL);
  g_signal_connect ((gpointer) sign, "clicked",
                    G_CALLBACK (on_sign_clicked),
                    NULL);
  g_signal_connect ((gpointer) division, "clicked",
                    G_CALLBACK (on_division_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) mul, "clicked",
                    G_CALLBACK (on_mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) subtrac, "clicked",
                    G_CALLBACK (on_subtrac_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) addition, "clicked",
                    G_CALLBACK (on_addition_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");
  GLADE_HOOKUP_OBJECT (window1, Clearentry, "Clearentry");
  GLADE_HOOKUP_OBJECT (window1, clear, "clear");
  GLADE_HOOKUP_OBJECT (window1, sign, "sign");
  GLADE_HOOKUP_OBJECT (window1, division, "division");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, mul, "mul");
  GLADE_HOOKUP_OBJECT (window1, subtrac, "subtrac");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, addition, "addition");

  return window1;
}

